import 'package:flutter/material.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:path_provider/path_provider.dart';
import 'dart:io';
import '../models/visit.dart';

class VisitDetailsScreen extends StatelessWidget {
  final Visit visit;

  const VisitDetailsScreen({super.key, required this.visit});

  // --- دالة توليد تقرير PDF الاحترافي ---
  Future<void> _generatePdf(BuildContext context) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          return [
            // ترويسة التقرير (يمكنك لاحقاً تغييرها لاسم عيادتك)
            pw.Header(
              level: 0,
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(
                    'Medical Visit Report',
                    style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold, color: PdfColors.blue800),
                  ),
                  pw.SizedBox(height: 4),
                  pw.Text(
                    'Date: ${visit.visitDate.toString().substring(0, 10)}',
                    style: const pw.TextStyle(fontSize: 14, color: PdfColors.grey700),
                  ),
                ],
              ),
            ),
            pw.SizedBox(height: 20),

            // 1. الإجراء الطبي / الشكوى الرئيسية
            _buildPdfSection('Procedure / Chief Complaint:', visit.procedure),

            // 2. الفحوصات
            if (visit.investigations.isNotEmpty)
              _buildPdfSection('Investigations & Imaging:', visit.investigations),

            // 3. العلاجات
            if (visit.treatments.isNotEmpty)
              _buildPdfSection('Prescribed Treatments:', visit.treatments),

            // 4. النصائح وإيقاف الأدوية
            if (visit.advices.isNotEmpty)
              _buildPdfSection('Medical Advices:', visit.advices),

            // 5. موعد الزيارة القادمة
            if (visit.nextVisitDate != null) ...[
              pw.SizedBox(height: 10),
              pw.Container(
                padding: const pw.EdgeInsets.all(10),
                decoration: pw.BoxDecoration(
                  color: PdfColors.blue50,
                  border: pw.Border.all(color: PdfColors.blue200),
                  borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
                ),
                child: pw.Row(
                  children: [
                    pw.Text('Next Visit Scheduled For: ', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                    pw.Text(visit.nextVisitDate!.toString().substring(0, 10)),
                  ],
                ),
              ),
            ],

            pw.SizedBox(height: 40),
            pw.Divider(),
            pw.SizedBox(height: 8),

            // تذييل التقرير
            pw.Text(
              'Generated by Medical-Records_Pro App',
              style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey),
              textAlign: pw.TextAlign.center,
            ),
          ];
        },
      ),
    );

    // حفظ ومشاركة PDF
    try {
      if (context.mounted) {
        await Printing.sharePdf(
          bytes: await pdf.save(),
          filename: 'visit_report_${visit.visitDate.toString().substring(0, 10)}.pdf',
        );
      }
    } catch (e) {
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error generating PDF: $e')),
        );
      }
    }
  }

  // أداة مساعدة لتنسيق أقسام الـ PDF
  pw.Widget _buildPdfSection(String title, String content) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(title, style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold, color: PdfColors.blueGrey800)),
        pw.SizedBox(height: 6),
        pw.Text(content, style: const pw.TextStyle(fontSize: 12, lineSpacing: 1.5)),
        pw.SizedBox(height: 16),
      ],
    );
  }

  // --- واجهة المستخدم (شاشة الهاتف) ---
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Visit Record'),
        backgroundColor: Colors.blue,
        foregroundColor: Colors.white,
        actions: [
          IconButton(
            icon: const Icon(Icons.picture_as_pdf),
            onPressed: () => _generatePdf(context),
            tooltip: 'Export to PDF',
          ),
        ],
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            // بطاقة تاريخ الزيارة
            Card(
              elevation: 2,
              child: ListTile(
                leading: const Icon(Icons.calendar_today, color: Colors.blue),
                title: const Text('Visit Date', style: TextStyle(fontWeight: FontWeight.bold)),
                subtitle: Text(
                  visit.visitDate.toString().substring(0, 10),
                  style: const TextStyle(fontSize: 16, color: Colors.black87),
                ),
              ),
            ),
            const SizedBox(height: 16),

            // الأقسام السريرية
            _buildSection(
              icon: Icons.medical_services,
              title: 'Procedure / Chief Complaint',
              content: visit.procedure,
              color: Colors.blue,
            ),

            if (visit.investigations.isNotEmpty)
              _buildSection(
                icon: Icons.biotech,
                title: 'Investigations & Imaging',
                content: visit.investigations,
                color: Colors.purple,
              ),

            if (visit.treatments.isNotEmpty)
              _buildSection(
                icon: Icons.medication,
                title: 'Treatments Prescribed',
                content: visit.treatments,
                color: Colors.green,
              ),

            if (visit.advices.isNotEmpty)
              _buildSection(
                icon: Icons.lightbulb,
                title: 'Medical Advices',
                content: visit.advices,
                color: Colors.orange,
              ),

            // موعد الزيارة القادمة
            if (visit.nextVisitDate != null)
              Card(
                elevation: 2,
                color: Colors.blue.shade50,
                child: ListTile(
                  leading: const Icon(Icons.event_available, color: Colors.blue),
                  title: const Text('Next Visit Scheduled', style: TextStyle(fontWeight: FontWeight.bold)),
                  subtitle: Text(
                    visit.nextVisitDate!.toString().substring(0, 10),
                    style: const TextStyle(fontSize: 16, color: Colors.blue, fontWeight: FontWeight.bold),
                  ),
                ),
              ),
          ],
        ),
      ),
    );
  }

  // ويدجت مساعد لعرض الأقسام في شاشة الهاتف
  Widget _buildSection({
    required IconData icon,
    required String title,
    required String content,
    required Color color, // تم تعديلها إلى Color لتجنب أخطاء البناء
  }) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 16),
      child: Card(
        elevation: 2,
        child: Padding(
          padding: const EdgeInsets.all(16),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                children: [
                  Icon(icon, color: color),
                  const SizedBox(width: 12),
                  Text(
                    title,
                    style: TextStyle(
                      fontSize: 16,
                      fontWeight: FontWeight.bold,
                      color: color,
                    ),
                  ),
                ],
              ),
              const Divider(height: 24),
              Text(
                content,
                style: const TextStyle(fontSize: 15, height: 1.5),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
